language: generic

sudo: required
service:
  - docker

before_install:
  - docker build -t dmohindru/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dmohindru/react-test npm test

after_success:
  - docker build -t dmohindru/multi-client ./client
  - docker build -t dmohindru/multi-nginx ./nginx
  - docker build -t dmohindru/multi-server ./server
  - docker build -t dmohindru/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push dmohindru/multi-client
  - docker push dmohindru/multi-nginx
  - docker push dmohindru/multi-server
  - docker push dmohindru/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'ap-southeast-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-2-402520608287'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
